### ISSUE TITLE
The second SIM card has no signal when its China Telecom

### ISSUE THREAD

**Issue by ykfq** [halogenOS/android_device_oneplus_oneplus3#1]
I'm looking for a ROM that has great performance and great battery life, when I found halogenOS I was so excited and then flash it,  but when the phone is up to use, I found that my SIM card of China Telecom didn't work !  I can't use the data network or even make a phone call. 

So, I post this issue and hope for the bug being fixed.

My phone is OnePlus 3T

**Comment by xdevs23** [comment]
Do other sim cards work in second slot? Did you try the first slot?
Please attach a log.

**Comment by JagravNaik** [comment]
@ykfq Make sure the APN is there in settings

**Comment by ykfq** [comment]
@xdevs23 
I didn't switch the two sim card because I didn't have any needle to take them out at that time, and I flashed another official hydrogenOS cause the next day was Monday and I had to use my phone for work

**Comment by ykfq** [comment]
@JagravNaik 
I could see the phone had recognize there are two SIM cards but the second cannot work properly, the signal icon was blank while the first was about 80% full.

**Comment by JagravNaik** [comment]
@ykfq Just go into sim settings and make sure that the APN is set for the second sim. Or is that from the same carrier?

**Comment by xdevs23** [comment]
Try checking APN as mentioned above or try swapping the sims and try other sims, too.
Just assuming that a specific carrier does not work in sim slot 2 without trying other sims and swapping slots is not really helpful.

**Comment by ykfq** [comment]
@xdevs23 @JagravNaik 
I'll chech it this weekend.
What I should mention is that the official hydrogenOS or lineageOS or RRN works fine without doing any trying.

**Comment by ykfq** [comment]
@xdevs23 @JagravNaik 
I flashed this [ROM](http://halogenos.org/upload/ROM/halogenOS/7/oneplus3/XOS_oneplus3_7.1.2_20170624.zip) agent yestoday, as you asked before, I swapped the SIMs and try again, but the problem was still there.
Blow is the result：

The two SIM cards name : (both have users almost one billion)
 **CTCC** : China Telecom Communication Corporation
 **CMCC** : China Mobile Communication Corporation

Testing steps :
-  The system info
https://moetu.org/image/JCmDq

- The two cards
https://moetu.org/image/JCQ6z

- The APN setting of **CTCC**
https://moetu.org/image/JzaVc

- The service and signal of CTCC -- No signal, out of service
https://moetu.org/image/JCJSN

- The service and signal of CMCC -- Normal
https://moetu.org/image/JC90H

- Try to call the service number of CMCC via CTCC -- No signal, no reaction
https://moetu.org/image/JCEiK

- Reset the settings
https://moetu.org/image/JzXMh

- Try to call the service number of CMCC via CTCC again -- still No signal and no reaction 
https://moetu.org/image/JC90H

- I flashed other ROM such as lingageOS dotOS and hydragenOS , there wasn't any problem.
I'm now using dotOS cause I have to use my phone today

**Comment by xdevs23** [comment]
Yeah but does the issue occur only on the second slot or also in the first one?

**Comment by ykfq** [comment]
It occurs in both of the two slots while the other card works fine in both.
The CTCC card was in slot 2 when create this issue, I swapped them yestoday , so now its in the first slot and the problem is still , I mentioned it 20 mins before.

Thanks

**Comment by xdevs23** [comment]
Alright so it's probably an issue with the shipped APNs. Will have to take a look at this after the 8.1 rebase.

**Comment by ykfq** [comment]
Ok, If the 8.1 stable version released, please let me know.
I'll keep chasing halgenOS for its "Great performance. Great battery life. Great stability".

**Comment by xdevs23** [comment]
We will let you know. As soon as we have working test builds with potential fixes for your issue, you can also try that. Note, that usually working test builds are also stable, they just contain experimental functionality and are more on the bleeding edge. They also need a bit more to boot right after flashing.

**Comment by ykfq** [comment]
Close it as it may had beed stopped developing and I dont't use it so far.
